name: release-check
on:
  issue_comment:
    types: [created]

jobs:
  release-check:
    name: Release on /merge command
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: dschep/install-poetry-action@v1.3
        with:
          version: 1.0.0
      - name: Release check
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          bump-files: pyproject.toml
          bump-command-base: ~/.poetry/bin/poetry version
