name: release-check
on:
  issue_comment:
    types: [created]

jobs:
  release-check:
    name: weat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: sdfasdffasd
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          bump-files: pyproject.toml
          bump-command-patch: poetry version patch
          bump-command-minor: poetry version minor
          bump-command-major: poetry version major
