name: release-check
on:
  pull_request_review_comment:
    types: [created]

jobs:
  release-check:
    name: weat
    runs-on: ubuntu-latest
    steps:
      - name: sdfasdffasd
        uses: ./

      # - name: Commit changes
      #   uses: EndBug/add-and-commit@v2
      #   with:
      #     force: true
      #     message: "[auto] Update compiled version"
      #     path: lib
      #     pattern: "*.js"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
